import Definitions.Def_adic_witness
import Definitions.Def_motivic_moore_reedy
import Definitions.Def_pointed_cyclic_carrier
import Definitions.Def_witness_background
import Solutions.Sol_thm_motivic_specialization

namespace SelmerCartanMotiveTowers

/-- Carrier-level motivic specialization of the witness (Theorem 38.5,
`W31-thm:common-source-motivic-span`), REVISED per Strategy A and
strengthened per external-verifier P1-4 and the M16 follow-up.

Assuming the witness arithmetic background (`WitnessBackground` §5: the
three pointed cyclic order-31 carrier lines — the arithmetic line from
the `K*` branch's `κ₅^root` identification, the marked source line, and
the motivic Moore line in the `I_*`-block), relative to the fixed source
marking, the arithmetic realization and the motivic realization give a
pointed carrier span
`L_*^{ar} ←ρ_*^{ar} L_*^{src} →ρ_*^{Mot} L_*^{Mot}`
of cyclic order-31 lines: the two arrows are *real* additive
isomorphisms preserving the distinguished generators (constructed via
the canonical `ZMod 31` identification, the paper's "unique
generator-preserving identification"), not an opaque span predicate.
The right-hand line is the fixed Moore carrier in the `I_*`-block of
the finite marked Moore–Reedy package; the proper 31-fold arithmetic
Massey value is recorded as a marking on this fixed motivic carrier.

CARRIER-LEVEL ONLY. The independent operation-level provenance (the
unipotent central extension and obstruction-gerbe correspondence) is
Theorem 38.1 (`thm_gerbe_provenance`); the paper is explicit that "the
carrier identification alone does not turn arithmetic cochains into
motivic correspondences."

REVISION NOTE (2026-10-09): The first draft was FALSE — it universally
quantified over an arbitrary `CarrierLine` type and unconstrained
`isOrder31`/`carrierSpan` predicates while the conclusion required them to
hold (countermodel: both constantly `False`). The Strategy A revision
took the paper's carrier-line data as background.

REVISION NOTE 3 (2026-10-10, verifier P1-4): the binders `W` and `M` are
no longer unused. `W` contributes its 31-torsion class via the proved
`witnessArithIso` (the cyclic subgroup generated by `W.terminalClass`,
of exact order 31, is canonically identified with the arithmetic carrier
`L_*^{ar}`); `marking_compat` proves the abstract three-line marking
compatibility. Both are counted as completed sub-items.

REVISION NOTE 4 (2026-10-10, verifier M16 follow-up): the M-linkage no
longer goes through a bare type bijection `hM : M.carrier ≃
bg.LMot.carrier` (which treated the whole opaque `M.carrier` as a
31-element line and gave it no additive structure or marking). It now
goes through `hB : blockSubobjectInterface M bg.LMot`, the named shape of
the paper's `I_*`-block identification (paper L16066–16107): the
designated block sub-object of `M.carrier`, its additive structure and
marking, the injective installation into `M.carrier`, and the pointed
identification with the marked motivic carrier. The conclusion's
`ρ_block` is a pointed additive isomorphism onto the actual block
sub-object, and `hB.embed ∘ ρ_block` is injective — the block is
faithfully installed in the original `M`. No additive structure or
marking is claimed for `M.carrier` itself; the Moore pair and
marked-ledger data are operation-level (Theorem 38.1), kept separate
from this carrier span. -/
theorem thm_motivic_specialization
    (W : adic_witness) (M : motivic_moore_reedy) (bg : WitnessBackground)
    (hB : blockSubobjectInterface M bg.LMot) :
    ∃ (ρ_ar : bg.Lsrc.carrier ≃+ bg.Lar.carrier)
      (ρ_mot : bg.Lsrc.carrier ≃+ bg.LMot.carrier)
      (ρ_W : ↥(AddSubgroup.zmultiples W.terminalClass) ≃+ bg.Lar.carrier)
      (ρ_block : bg.Lsrc.carrier ≃+ hB.blockCarrier),
      ρ_ar bg.Lsrc.gen = bg.Lar.gen ∧
      ρ_mot bg.Lsrc.gen = bg.LMot.gen ∧
      ρ_W ⟨W.terminalClass, AddSubgroup.mem_zmultiples _⟩ = bg.Lar.gen ∧
      ρ_block bg.Lsrc.gen = hB.blockMark ∧
      Function.Injective (hB.embed ∘ ρ_block) :=
  SelmerCartanMotiveTowers.sol_thm_motivic_specialization W M bg hB

end SelmerCartanMotiveTowers
