import Mathlib.Algebra.Squarefree.Basic
import Definitions.Def_finite_ordered_support

namespace SelmerCartanMotiveTowers

/-- The support-functorial motivic Moore–Reedy target for a finite ordered
support `S` and an odd squarefree coefficient order `N`:
`M_{S,N}^{Mot,MR} := B_S^{Mot} ⊕ ⊕_{I ⊆ S, |I| ≥ 3} ⊕_{(A,B) ∈ P^→(I)}
|V_{I;A,B}^{Mot,ch}|`,
together with its dg correspondence subalgebra
`M_{S,N}^{Mot,MR} ⊆ REnd(M_{S,N}^{Mot,MR})` generated by the Boolean support
projections and shifts `U_i`, the channel matrix units, the root Moore pair,
and the cyclotomic transfer correspondence. The carrier and the algebra are
opaque here; the support-deletion maps `P_T^S` are supplied separately.
The standing "odd squarefree" hypothesis on `N` is recorded as fields
(`coeffOrder_odd`, `coeffOrder_squarefree`).
(Definition P2M-def:genuine-motivic-rees-cartan, §19; §32.) -/
structure motivic_moore_reedy where
  support : finite_ordered_support
  coeffOrder : ℕ
  coeffOrder_odd : Odd coeffOrder
  coeffOrder_squarefree : Squarefree coeffOrder
  carrier : Type
  corrAlgebra : Type

end SelmerCartanMotiveTowers
