import Definitions.Def_moore_cohomology_line

namespace SelmerCartanMotiveTowers

/-- Formal/filtered alignment at depth two (Theorem 8.21,
`P1C-thm:formal-filtered-alignment`), strengthened per external-verifier
P1-4: the universal exact-order Moore line `L^{Moore}_{p;q²}` (the cohomology
`H^d` of the Moore complex, concretely `ZMod (p*q^2)`, generated by
`[B_{2,1}]`) and the primitive filtered confluence line
`L^{conf}_{p;q²} = L_p × L^{conf}_{q²}` (concretely
`ZMod p × ZMod (q^2)`, generated by `(b_p, κ̃ mod q²)`) admit a unique
pointed `AddEquiv` sending generator to generator. Under q-primary
reduction it sends the universal Moore generator to the residual
repeated-input secondary generator `κ̄` (paper L2235–2260;
`P1C-thm:formal-pq2-order`, `P1C-thm:pq2-crt-confluence`,
`P1C-thm:filtered-q2-line`).

REVISION NOTE (2026-10-10, verifier P1-4 M3): the proof declares
`hrange := mooreDiff_range p q`, `hcoh := moore_cohomology p q`, and
`hkappa := confGen_kappa_tilde p q hI`, BUT these three local `have`s are
not consumed by the subsequent derivation — the actual proof uses only
the CRT `RingEquiv` (`ZMod.chineseRemainder`) and the proved
`qPrimaryRed_kappa_tilde`. The generator identifications
(`1 = [B_{2,1}]` via `hcoh`, `(1,1).2 = [κ̃]` via `hkappa`) appear only
in comments, not in proof steps; the named Props
(`mooreGen_is_cohomology_class`, `PrimitiveFilteredInterface`) thread no
actual quotient/class argument into the construction. The complete
generator chain `[1] → mooreGen → confGen` is therefore NOT closed —
the current result is the CRT equivalence on the `ZMod` model plus the
proved `q`-primary reduction law.
-/
theorem sol_thm_formal_filtered_alignment
    (p q : ℕ) (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) :
    ∃! e : moore_line p q ≃+ conf_line p q,
      e (mooreGen p q) = confGen p q ∧
      qPrimaryRed p q (e (mooreGen p q)) = residualGen q := by
  -- Step 1 (verifier P1-4): the Moore complex differential has image exactly
  -- the boundaries; cohomology is `ℤ ⧸ mooreBoundaries ≃+ moore_line`.
  have hrange := mooreDiff_range p q
  have hcoh := moore_cohomology p q
  -- The generator `[B_{2,1}]` is the class of `1 : ℤ`; `mooreGen` is its
  -- image under `moore_cohomology` (see `mooreGen_is_cohomology_class`).
  -- Step 2: the `W_q`-interface for the `q²`-component.
  have hq2 : NeZero q := ⟨hq.ne_zero⟩
  have hI := concreteFilteredInterface q
  -- `(confGen p q).2` is `[κ̃]` under the primitivity identification.
  have hkappa := confGen_kappa_tilde p q hI
  -- Coprimality for CRT: distinct primes give `Coprime p (q^2)`.
  have hcop : Nat.Coprime p (q ^ 2) :=
    Nat.Coprime.pow_right 2 ((Nat.coprime_primes hp hq).mpr hpq)
  -- The CRT equivalence, as an `AddEquiv`.
  let e0 : moore_line p q ≃+ conf_line p q :=
    (ZMod.chineseRemainder hcop).toAddEquiv
  -- It is pointed: `1 ↦ (1, 1)`, via the underlying `RingEquiv`'s `map_one`.
  -- Here `1 = mooreGen` is `[B_{2,1}]` via `hcoh`, and `(1,1) = confGen`
  -- has second component `[κ̃]` via `hkappa`.
  have he1 : e0 (mooreGen p q) = confGen p q :=
    (ZMod.chineseRemainder hcop).map_one
  -- q-primary reduction sends the image to the residual generator `κ̄`:
  -- via `qPrimaryRed_kappa_tilde`, this is `(κ̃ mod q²) mod q = κ̄`.
  have hred : qPrimaryRed p q (e0 (mooreGen p q)) = residualGen q := by
    rw [he1]
    exact qPrimaryRed_kappa_tilde p q hI
  refine ⟨e0, ⟨he1, hred⟩, ?_⟩
  -- Uniqueness: an AddEquiv out of `ZMod (p*q^2)` is fixed by its value on `1`.
  intro e' ⟨he', _⟩
  have hfun : ∀ y : moore_line p q, e' y = e0 y := by
    intro y
    have : NeZero (p * q ^ 2) :=
      ⟨mul_ne_zero hp.ne_zero (pow_ne_zero 2 hq.ne_zero)⟩
    have hy : y = y.val • (mooreGen p q) := by
      show y = y.val • (1 : ZMod (p * q ^ 2))
      rw [nsmul_eq_mul, mul_one, ZMod.natCast_zmod_val]
    conv_lhs => rw [hy]
    rw [map_nsmul, he', ← he1, ← map_nsmul, ← hy]
  exact AddEquiv.ext hfun

end SelmerCartanMotiveTowers
