import Definitions.Def_moore_cohomology_line

namespace SelmerCartanMotiveTowers

/-- Formal/filtered alignment at depth two (Theorem 8.21,
`P1C-thm:formal-filtered-alignment`), strengthened per external-verifier
P1-4: the universal exact-order Moore line `L^{Moore}_{p;q²}` (the cohomology
`H^d` of the Moore complex, concretely `ZMod (p*q^2)`, generated by
`[B_{2,1}]`) and the primitive filtered confluence line
`L^{conf}_{p;q²} = L_p × L^{conf}_{q²}` (concretely
`ZMod p × ZMod (q^2)`, generated by `(b_p, κ̃ mod q²)`) admit a unique
pointed `AddEquiv` sending generator to generator. Under q-primary
reduction it sends the universal Moore generator to the residual
repeated-input secondary generator `κ̄` (paper L2235–2260;
`P1C-thm:formal-pq2-order`, `P1C-thm:pq2-crt-confluence`,
`P1C-thm:filtered-q2-line`). -/
theorem sol_thm_formal_filtered_alignment
    (p q : ℕ) (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) :
    ∃! e : moore_line p q ≃+ conf_line p q,
      e (mooreGen p q) = confGen p q ∧
      qPrimaryRed p q (e (mooreGen p q)) = residualGen q := by
  -- Coprimality for CRT: distinct primes give `Coprime p (q^2)`.
  have hcop : Nat.Coprime p (q ^ 2) :=
    Nat.Coprime.pow_right 2 ((Nat.coprime_primes hp hq).mpr hpq)
  -- The CRT equivalence, as an `AddEquiv`.
  let e0 : moore_line p q ≃+ conf_line p q :=
    (ZMod.chineseRemainder hcop).toAddEquiv
  -- It is pointed: `1 ↦ (1, 1)`, via the underlying `RingEquiv`'s `map_one`.
  have he1 : e0 (mooreGen p q) = confGen p q :=
    (ZMod.chineseRemainder hcop).map_one
  -- q-primary reduction sends the image to the residual generator.
  have hred : qPrimaryRed p q (e0 (mooreGen p q)) = residualGen q := by
    rw [he1]
    exact (qPrimaryRed p q).map_one
  refine ⟨e0, ⟨he1, hred⟩, ?_⟩
  -- Uniqueness: an AddEquiv out of `ZMod (p*q^2)` is fixed by its value on `1`.
  intro e' ⟨he', _⟩
  have hfun : ∀ y : moore_line p q, e' y = e0 y := by
    intro y
    have : NeZero (p * q ^ 2) :=
      ⟨mul_ne_zero hp.ne_zero (pow_ne_zero 2 hq.ne_zero)⟩
    have hy : y = y.val • (mooreGen p q) := by
      show y = y.val • (1 : ZMod (p * q ^ 2))
      rw [nsmul_eq_mul, mul_one, ZMod.natCast_zmod_val]
    conv_lhs => rw [hy]
    rw [map_nsmul, he', ← he1, ← map_nsmul, ← hy]
  exact AddEquiv.ext hfun

end SelmerCartanMotiveTowers
