import Definitions.Def_adic_witness
import Definitions.Def_motivic_moore_reedy
import Definitions.Def_pointed_cyclic_carrier
import Definitions.Def_witness_background

namespace SelmerCartanMotiveTowers

/-- The witness's arithmetic line, identified with a pointed cyclic carrier.

The witness `W` carries `W.terminalClass` of exact additive order 31
(`terminalClassOrder`). The subgroup it generates is therefore cyclic of
order 31, and the canonical `ZMod 31` identification gives an additive
isomorphism with any pointed cyclic order-31 carrier — in particular
`bg.Lar`, the paper's arithmetic line from the `K*` branch. The
isomorphism sends the witness's class to the carrier's distinguished
generator.

This is the type-level content of the paper's "`K*`-branch arithmetic
line" identification: the 31-torsion the witness detects IS the
arithmetic carrier line, not an unrelated group that happens to have
31-torsion. It is PROVED from `W`'s data (exact order 31), not assumed. -/
theorem witnessArith_mem (W : adic_witness)
    (x : ↥(AddSubgroup.zmultiples W.terminalClass)) :
    x ∈ AddSubgroup.zmultiples
      (⟨W.terminalClass, AddSubgroup.mem_zmultiples _⟩ :
        ↥(AddSubgroup.zmultiples W.terminalClass)) := by
  obtain ⟨k, hk⟩ := AddSubgroup.mem_zmultiples_iff.mp x.property
  rw [AddSubgroup.mem_zmultiples_iff]
  refine ⟨k, Subtype.ext ?_⟩
  push_cast
  exact hk

/-- Canonical identification of the witness's 31-torsion line with a
pointed cyclic order-31 carrier (via `ZMod 31`). -/
noncomputable def witnessArithIso (W : adic_witness) (L : pointed_cyclic_carrier) :
    ↥(AddSubgroup.zmultiples W.terminalClass) ≃+ L.carrier :=
  (zmodAddEquivOfGenerator (witnessArith_mem W)
    (by rw [Nat.card_zmultiples, W.terminalClassOrder])).symm.trans
    (zmodAddEquivOfGenerator L.mem_gen L.nat_card_eq)

/-- The witness–arithmetic identification is pointed: it sends the
witness's class to the carrier's distinguished generator. -/
theorem witnessArithIso_apply_class (W : adic_witness) (L : pointed_cyclic_carrier) :
    witnessArithIso W L ⟨W.terminalClass, AddSubgroup.mem_zmultiples _⟩ = L.gen := by
  show (zmodAddEquivOfGenerator L.mem_gen L.nat_card_eq)
      ((zmodAddEquivOfGenerator (witnessArith_mem W) _).symm
        ⟨W.terminalClass, AddSubgroup.mem_zmultiples _⟩) = L.gen
  rw [zmodAddEquivOfGenerator_symm_apply_generator, zmodAddEquivOfGenerator_apply_one]

/-- The markings (distinguished generators) are compatible across the
whole pointed span: the induced identification `L_*^{ar} → L_*^{Mot}`
(via the marked source line) sends the arithmetic marking to the motivic
marking. This is the carrier-level content of the paper's "marked" span:
the three lines are not merely abstractly isomorphic, they are identified
as *pointed* lines. -/
theorem marking_compat (bg : WitnessBackground) :
    ((bg.Lsrc.canonicalIso bg.Lar).symm.trans
      (bg.Lsrc.canonicalIso bg.LMot)) bg.Lar.gen = bg.LMot.gen := by
  have h1 : (bg.Lsrc.canonicalIso bg.Lar).symm bg.Lar.gen = bg.Lsrc.gen := by
    have h := bg.Lsrc.canonicalIso_apply_gen bg.Lar
    calc (bg.Lsrc.canonicalIso bg.Lar).symm bg.Lar.gen
        = (bg.Lsrc.canonicalIso bg.Lar).symm
            ((bg.Lsrc.canonicalIso bg.Lar) bg.Lsrc.gen) := by rw [← h]
      _ = bg.Lsrc.gen := AddEquiv.symm_apply_apply _ _
  rw [AddEquiv.trans_apply, h1, bg.Lsrc.canonicalIso_apply_gen]

/-- Solution for Theorem 38.5 (`thm_motivic_specialization`), M16.

The three carrier lines are `pointed_cyclic_carrier`s (background §5:
the arithmetic line from the `K*` branch, the marked source line, the
motivic Moore line). The pointed span
`L_*^{ar} ← L_*^{src} → L_*^{Mot}` is *constructed*, not assumed: any two
pointed cyclic order-31 carriers admit a canonical generator-preserving
isomorphism (`pointed_cyclic_carrier.canonicalIso`, via `ZMod 31`),
which is the paper's "unique generator-preserving identification".

CARRIER-LEVEL ONLY. The independent operation-level provenance
(unipotent central extension, obstruction gerbe) is Theorem 38.1
(`thm_gerbe_provenance`); the paper is explicit that "the carrier
identification alone does not turn arithmetic cochains into motivic
correspondences."

REVISION NOTE 3 (2026-10-10, verifier P1-4): the binders `W` and `M` are
no longer unused.
- `W` contributes its 31-torsion class: `witnessArithIso` canonically
  identifies the cyclic subgroup generated by `W.terminalClass` with the
  arithmetic carrier `bg.Lar`, sending the class to the distinguished
  generator (`witnessArithIso_apply_class`). This is the type-level
  content of the paper's "`K*`-branch arithmetic line".
- `M` is linked by the hypothesis `hM : M.carrier ≃ bg.LMot.carrier`,
  the background identification of the motivic Moore carrier as the
  `I_*`-block of the finite marked Moore–Reedy package (paper
  L16066–16107). It is a hypothesis (not a construction) because
  `M.carrier` is opaque — the paper's block identification is background
  per Strategy A. The conclusion's `ρ_M` transports the motivic span leg
  to `M.carrier` along this identification, so the marked source line is
  identified with `M`'s carrier.
- `marking_compat`: the markings (distinguished generators) agree across
  the whole span, including the induced `L_*^{ar} → L_*^{Mot}`
  identification. -/
theorem sol_thm_motivic_specialization
    (W : adic_witness) (M : motivic_moore_reedy) (bg : WitnessBackground)
    (hM : M.carrier ≃ bg.LMot.carrier) :
    ∃ (ρ_ar : bg.Lsrc.carrier ≃+ bg.Lar.carrier)
      (ρ_mot : bg.Lsrc.carrier ≃+ bg.LMot.carrier)
      (ρ_W : ↥(AddSubgroup.zmultiples W.terminalClass) ≃+ bg.Lar.carrier)
      (ρ_M : bg.Lsrc.carrier ≃ M.carrier),
      ρ_ar bg.Lsrc.gen = bg.Lar.gen ∧
      ρ_mot bg.Lsrc.gen = bg.LMot.gen ∧
      ρ_W ⟨W.terminalClass, AddSubgroup.mem_zmultiples _⟩ = bg.Lar.gen ∧
      ρ_M = (bg.Lsrc.canonicalIso bg.LMot).toEquiv.trans hM.symm :=
  ⟨bg.Lsrc.canonicalIso bg.Lar, bg.Lsrc.canonicalIso bg.LMot,
    witnessArithIso W bg.Lar,
    (bg.Lsrc.canonicalIso bg.LMot).toEquiv.trans hM.symm,
    bg.Lsrc.canonicalIso_apply_gen bg.Lar,
    bg.Lsrc.canonicalIso_apply_gen bg.LMot,
    witnessArithIso_apply_class W bg.Lar,
    rfl⟩

end SelmerCartanMotiveTowers
